### PR TITLE
Docs: Remove REPL markers from example

### PR DESCRIPTION
**Pull request by eoghanmurray**
The REPL markers are confusing me; I don't think you can type async code into the REPL like that?
Also the example hadn't indented the `with` block.

### CODE REVIEW

**Comment by NoneGG** [comment]
Merged, thanks~

**Comment by Fogapod** [comment]
What about removing them from all other places as well for consistency? For example, README.md

**Comment by eoghanmurray** [comment]
@Fogapod I didn't notice them elsewhere ... I believe I made my edits via github if you wanna do the same in a new pull request?

**Comment by Fogapod** [comment]
I already created a PR for this

**Pull request merged**
