### PR TITLE
fix: importation of CancelledError with Python 3.7+

### PR DESCRIPTION
**Pull request by meakio**
CancelledError from Python 3.7+ is move from futures subpackage to the root of asyncio package.

### CODE REVIEW

**Comment by fvlima** [comment]
> CancelledError from Python 3.7+ is move from futures subpackage to the root of asyncio package.

This problem occurs only in python 3.8. I just installed now with python 3.7.5 and it was ok

**Comment by fvlima** [comment]
I think that would be interesting to change the `install_requires` section [1] to consider python versions 3.7 and 3.8. And also, include this versions in `classifiers` section [2]

1 - https://github.com/NoneGG/aredis/blob/master/setup.py#L146 
2 - https://github.com/NoneGG/aredis/blob/master/setup.py#L133-L135

**Comment by meakio** [comment]
@fvlima I made the changes in the code.

Because I was on the circleci config file, I also updated the redis cluster images. Do you want to undo this modification ?

**Comment by NoneGG** [comment]
> Because I was on the circleci config file, I also updated the redis cluster images. Do you want to undo this modification ?

I think it is fine~

@meakio @fvlima 
This pr will be merged, thanks a lot~

**Comment by fvlima** [comment]
> @fvlima I made the changes in the code.

It was ok! thank you for this improvements

**Pull request merged**
